### ISSUE TITLE
[web3t] Fix inconsistent pricing

### ISSUE THREAD

**Issue by geoknee** [statechannels/monorepo#1148]
If I download a file that claims to "cost" 1300 wei, why do I end up paying far more than that? (Paying a little more is expected and probably ok, since we are using a basic buffered payment system).

**Comment by geoknee** [comment]
Might get fixed alongside #1133 .

**Comment by spersico** [comment]
When the seeder blocks the leecher and then gets re-enabled, the leecher re-sends a lot of requests (some repeated) that shouldn't be resent, paying for stuff he already paid a bunch of times.

This gets worse when the leecher gets blocked several times (for big files, for example).

It seems that we didn't notice before, because the difference was pretty small 'till last week (because I used small amounts), and before that, the money was totally fake :confused:  .
