### ISSUE TITLE
Should xstate-wallet export functionality

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1177]
At the moment, the _simple-hub_ relies on [xstate-wallet types and message serialization utilities](https://github.com/statechannels/monorepo/blob/master/packages/simple-hub/src/wallet/index.ts#L3). Should these be exported from the _xstate-wallet_? Should a separate package hold these? Or do we think that these are _xstate-wallet_ internals that should not be exposed outside of the package?

**Comment by andrewgordstewart** [comment]
Since the workflows are now being defined in `xstate-wallet`, it makes sense for _some things_ to be exported from `xstate-wallet` right now.

**Comment by kerzhner** [comment]
@andrewgordstewart Do you have any specific exports in mind?

**Comment by andrewgordstewart** [comment]
`support-state`, `depositing`, `virtual-funding-as-hub`, etc

**Comment by tomclose** [comment]
I'm of the "[duplication over premature abstraction](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction?duplication)" school of thought. I'd rather see these types and utilities copied across, rather than introduce dependencies between packages, or deal with the overhead of pulling them out into a new package. That way, teams working in different packages can code to their own use-cases, without having to worry about other consumers (e.g avoiding issues like https://github.com/statechannels/monorepo/pull/1168#discussion_r390485798).

When we're not developing so quickly, and the dust settles, it should be clearer which utilities etc. should be pulled up into a shared package.
