### ISSUE TITLE
Deposits start before both players accept joining/creating a channel

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1237]
It seems that after player A selects create channel they're prompted to deposit, even if player B has not chosen to join the channel yet.

**Comment by andrewgordstewart** [comment]
It's because of [this commit](https://github.com/statechannels/monorepo/commit/870455dda98029400b2f7407512cb9fefb4dae76), which explains its reasoning.

We probably want to revisit that reasoning. Technically, even if the app is malicious, the joiner's funds are not at risk, since the pop-up prevents the joiner from depositing. But, it does aggravate the creator, who might end up depositing before the joiner refuses to join the channel. Therefore, the wallet should, as a courtesy, refrain from signing the first state until the user clicks ok.

We should defer this issue since it is not a part of the workflow hit by web3torrent.

**Comment by lalexgap** [comment]
This has been resolved by other changes.
