### ISSUE TITLE
Investigate idempotent workflows

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1289]
Investigate what is required to be able to restart our workflows based on existing objectives and  have them resume progress.

This would mean we wouldn't have to store the actual workflows as on browser restart we could just spawn workflows for objectives and rely on the workflows to reach the correct state.

Initial discussion and design here: https://www.notion.so/State-Channels-4cc770686d05438bb23b3c37f4069d7e?p=4ac481f7b3134f4495d95d455f3542a3

**Comment by junjizhi** [comment]
Looking at https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/store/types.ts#L125, we have the following objectives

```typescript
export type Objective = OpenChannel | VirtuallyFund | FundGuarantor | FundLedger | CloseLedger;
```

My understanding is that each workflow is like a transaction. If a browser closes before a workflow is finished, there shouldn't be any side effects that would impact the next workflow. That's how a workflow can be restart-able. So we have to make sure we "commit" any permanent changes at the end of the transaction.

Some possible side effects I can think of are 1) changes to any variables in store, 2) changes to any on-chain values. If there are changes, when the workflow restarts, they should be overwritten.

@snario @lalexgap Do you think I am heading to the right direction?

**Comment by snario** [comment]
I think that sounds about right. An example of something which would need to be true is that for workflows which trigger an on-chain transaction to occur like depositing some funds, or creating a challenge, when the workflow is restarted it should have observed that there is no need to deposit more funds or trigger another challenge transaction.

The various state machines were written with this being the aspiration, but my understanding is that there may be some examples where this is not the case that are not tested.

**Comment by junjizhi** [comment]
> there may be some examples where this is not the case that are not tested.

Like the `OpenChannel` objective, the aborted workflow may have created a channel already. Can the restarted workflow observe the created channel? This might be the exception case.

@snario

**Comment by junjizhi** [comment]
When looking at the `FundLedger` objective, we [store the `ledgerId` in the store](https://github.com/statechannels/monorepo/blob/master/packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts#L231), which is created from the `createChannel` call. 

To make sure this workflow is idempotent, we either need to

- pre-generate channel id and store it (meaning that we would pass the channel id to `createChannel()` call instead of generating the new one inside)

or 

- find a way to determine an existing ledger has already been created. If we can assume participants won't create many ledger channels in a short amount of time, we may use the `participants` list as a key. But don't know how good is this assumption.

**Comment by andrewgordstewart** [comment]
> * find a way to determine an existing ledger has already been created. If we can assume participants won't create many ledger channels in a short amount of time, we may use the `participants` list as a key. But don't know how good is this assumption.

The `store.getLedger(participantId)`, where `participantId` is the participant ID of the hub, would return the channel store entry for a ledger channel with the hub (if it exists).

**Comment by andrewgordstewart** [comment]
During the discussion @junjizhi, we decided a good strategy is to focus on the _end_ workflows: `conclude-channel`. The reasoning is:
1. an idempotent `conclude-channel` is significant progress towards making the guarantee "We'll always get your funds out", which seems more like a level 0 or level 1 goal than a level 2 goal
2. `conclude-channel`, and its invoked services, do not rely on objectives. Objectives are not persisted, because they are not fully specced out, and naively persisting them currently triggers unwanted workflows.
3. It avoids answering the question "Do I actually want to continue funding this channel?", which can easily happen eg. in web3torrent, when I reload the page and no longer want to download a file.
4. It is _required_ if the answer to "Do I actually want to continue funding this channel?" is no.

I will make a couple of other cards for organizing the goal of an idempotent `conclude-channel` workflow.

**Comment by junjizhi** [comment]
Another thing that came out of the discussion with @andrewgordstewart is
- If we want to make the other workflows (e.g., `FundLedger` mentioned above) idempotent, we may use the pair of `(myID, peerID)` as a key to retrieve the last created channel, instead of creating a new one each time.

**Comment by junjizhi** [comment]
@andrewgordstewart 


> 3. It avoids answering the question "Do I actually want to continue funding this channel?", which can easily happen eg. in web3torrent, when I reload the page and no longer want to download a file.
> 4. It is required if the answer to "Do I actually want to continue funding this channel?" is no.

I have two questions: 

- What's _required_? 
- When should `conclude-channel` get invoked? 

If I understand it correctly, when I reload the page, the app will check the store and find an old objective that indicates an abandoned workflow, then it prompts the user: "Do I actually want to continue funding this channel?".  If user's answer is no, then `conclude-channel` starts. Right?

**Comment by andrewgordstewart** [comment]
> * What's _required_?

Edited 4 to clarify.

> If I understand it correctly, when I reload the page, the app will check the store and find an old objective that indicates an abandoned workflow, then it prompts the user: "Do I actually want to continue funding this channel?". If user's answer is no, then `conclude-channel` starts. Right?

This seems pretty reasonable, with the caveat that we currently do not store objectives. (Let me make an issue describing that problem.)

So, perhaps to answer your question, if we _were_ to store objectives, and we always answered
> Do I actually want to continue funding this channel?

with "No.", then the answer to
> When should `conclude-channel` get invoked?

could be: `conclude-channel` is invoked when either:
1. the application workflow decides it should be invoked.
2. the wallet was just initialized, and there is an application channel in the store

In (2), these could be found by looking at the `applicationSite` field.
- in the dexie backend, something like
```
backend._db['channels'].where('applicationSite').notEqual(undefined);
```
- in the memory backend, something like
```
_.filter(_.values(backend._channels), entry => (typeof entry.applicationSite === 'string')))
```

This also skirts the `Objective` issue, and is also more explicitly what we want: the creator doesn't actually get an `OpenChannel` objective (maybe this should/will change), so starting the `conclude-channel` workflow based on the presence of objectives would not work for the creator.

**Comment by junjizhi** [comment]
> This seems pretty reasonable, with the caveat that we currently do not store objectives. (Let me make an issue describing that problem.)

Can you link the issue here? @andrewgordstewart

**Comment by junjizhi** [comment]
Based on the discussion above, with all the created issues as a result, we can end the investigation and move on.
