### ISSUE TITLE
[monorepo] Configure Renovate Noise Reduction

### ISSUE THREAD

**Issue by Alonski** [statechannels/monorepo#134]
Renovate creates many PRs for updates and this can easily get overwhelming.

A solution to this is setting up settings for "Noise Reduction":
https://docs.renovatebot.com/noise-reduction/

Some recommendations:
Package Grouping
Automerging (If tests pass)
Branch automerging (This doesn't create a PR at all, a branch is created with the updates, if tests pass Renovate will push the changes into `master/next` without a PR. This can dramatically reduce the noise we get from Renovate provided we have good test coverage)

**Comment by andrewgordstewart** [comment]
We already group packages by extending [`config:base`](https://github.com/statechannels/monorepo/blob/master/renovate.json#L2), which extends [`group:monorepos`](https://docs.renovatebot.com/presets-group/#groupmonorepos) and [`group:recommended`](https://docs.renovatebot.com/presets-group/#grouprecommended). I'm not sure if [`group:all`](https://docs.renovatebot.com/presets-group/#groupall) is the best idea.

We also now extend [group:allNonMajor`](https://docs.renovatebot.com/presets-group/#groupallnonmajor), which means we will only get individual PRs for major version updates. This probably makes sense, since there could easily be breaking changes. It also means that the noise experienced this weekend might be a one-time occurrence, getting all deps and devDeps to the latest major version. I would guess that not many packages are introducing major version updates on a weekly basis.

That being said, bumping up the minor version of one of our packages broke tests. I've spent a couple of hours already trying to debug this. Given this, I'm not sure of the value of bumping minor versions without a specific reason. Should we only use renovate bot to ensure we are always using the latest patches, and not more? Or do we get a measurable benefit from also bumping minor versions on a regular basis?

**Comment by andrewgordstewart** [comment]
> Automerging (If tests pass)
> Branch automerging

Currently, we only run tests on packages that have been changed in the current branch. ([This PR](https://github.com/statechannels/monorepo/pull/135) also separates out some build steps, to only run them in packages that have changed.) I don't think this conflicts with these strategies -- or at least, they don't create any additional issues with it -- but it's something to keep in mind.

I think that automerging is already enabled, but is prevented by branch protection rules requiring a review. That rule in its current form also prevents automerging. We could edit this rule to exempt the renovate bot.
