### ISSUE TITLE
Allow easy ledger withdrawal from web3 torrent

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1411]
Right now the withdraw button only shows up in certain conditions, making it hard to actually withdraw. We should have the withdraw button accessible whenever the user has secured a budget.

This is pretty related #1382 and could be solved with that.

**Comment by junjizhi** [comment]
> Right now the withdraw button only shows up in certain conditions, making it hard to actually withdraw.

I think `SiteBudgetTable` shows up whenever `budgetCache` is not empty. Is there a case where the cache is empty but you want to withdraw?

**Comment by geoknee** [comment]
I think the point is that `SiteBudgetTable` itself is only displayed on the `File` page. So if you computer crashes, but you return to the homepage at some later time, you can only see / administer your budget by going to that page, which currently requires e.g.  uploading a file or pasting a magnet link.

Since web3torrent does not persist any data, we wouldn't want to rely on the `budgetCache` alone. 
One solution would be, when the app's `payment-channel-client` first `enables`,  it repopulates its caches using `getBudget` and `getState`.
