### ISSUE TITLE
[web3torrent] Connected to x peers after file exchange

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#1463]
I am not sure if the behavior is a bug or if the app should work this way. After the leecher and the seeder finish exchanging a file, "Connected to 1 peers" UI remains (without going to 0)
<img width="967" alt="Screen Shot 2020-04-16 at 3 16 20 PM" src="https://user-images.githubusercontent.com/1062379/79512319-0b826a00-7ff6-11ea-9661-7f739c155664.png">

**Comment by snario** [comment]
I think this is expected behaviour right @spersico?

**Comment by spersico** [comment]
It's a mix of conditions: basically, we take a really long time to delete wires (just in case), AND we use the internal `peers` object from webtorrent because it's more representative, AND we don't update automatically, relying instead in "pushed updates" to the UI.
.... I think the last one is the one responsible for this, but I'm not sure. I can take a look
