### ISSUE TITLE
[e2e-tests] Shell script skips withdraw test

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1609]
If I do
`cd $MONOREPO_ROOT/packages/e2e-tests && yarn test:e2e:w3t` then the `withdraw.test.ts` is skipped:
```
packages/e2e-tests on  ags/simple-hub-ganache-setup [$!] on ☁️  us-west-1 took 1m1s 
❯ yarn test:e2e:w3t-with-hub
...

Test Suites: 1 skipped, 1 passed, 1 of 2 total
Tests:       1 skipped, 1 passed, 2 total
Snapshots:   0 total
Time:        24.801s
Ran all test suites matching /web3torrent/i.
```

Also happens [on circle](https://app.circleci.com/pipelines/github/statechannels/monorepo/5659/workflows/95f5b16b-88bb-4c19-a2d5-229f0358de9a/jobs/21907/parallel-runs/0/steps/0-106)

**Comment by geoknee** [comment]
I don't think this is a consequence of the shell script. The withdraw test is designed to skip itself when we aren't using virtual funding (since there is nothing to withdraw in that case, "withdraw" currently meaning "withdraw from the ledger channel"). If you had run `yarn test:e2e:w3t-with-hub`, you would have seen both tests run.
