### ISSUE TITLE
Rps integration test flicker

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1676]
See https://app.circleci.com/pipelines/github/statechannels/monorepo/5910/workflows/bfd40557-e3b9-48f3-9572-44d19f9eca66/jobs/23560/steps

**Comment by kerzhner** [comment]
Just saw this test fail [here](https://app.circleci.com/pipelines/github/statechannels/monorepo/5961/workflows/0e938794-bee2-4a12-8b2b-90dcdea1e42a/jobs/23915).

**Comment by snario** [comment]
Curious if @geoknee you have any recent insights on this?

**Comment by geoknee** [comment]
@snario This test failed last 3 days ago, for a different reason: https://app.circleci.com/pipelines/github/statechannels/monorepo/6599/workflows/2a43f493-fbe6-43d9-b6d7-f37659f79f8a/jobs/28298
By my reckoning it has since passed 25+ times. 

There were some recent changes to RPS, but I don't know if they would have an impact on the flicker frequency.
