### ISSUE TITLE
Investigate what Gas Limit we should use

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#1940]
We should investigate what we should set the gas limit to. See discussion [here](https://github.com/statechannels/monorepo/pull/1894)

Ideally I think we should let metamask handle this but I think we ran into issues when not specifying a gas limit (perhaps due to ganache not estimating gas correctly?) https://ethereum.stackexchange.com/questions/33389/how-is-gas-limit-estimated-by-metamask

**Comment by geoknee** [comment]
See #1950

**Comment by geoknee** [comment]
It is much more preferable if we can rely on ethers to handle the gas limit estimation. This is because the hub, as well as our e2e tests when dappeteer is disabled (as it is now), do not use metamask.

I noticed that the `simple-hub`'s transaction seemed to get the gas limit spot on (100% of gas lmit is used in its transactions). It does not use metamask, and it does not specify a gas limit itself. So I believe ethers is capable of handling this for us, as long as we don't override it.

**Comment by geoknee** [comment]
https://github.com/ethers-io/ethers.js/issues/484#issue-430822309

**Comment by geoknee** [comment]
Via #1950
