### ISSUE TITLE
Active channels ending in the "disconnected" state

### ISSUE THREAD

**Issue by snario** [statechannels/monorepo#1992]

**Comment by tomclose** [comment]
We initially thought this was a deadlock issue, but I'm not so sure. In the list below, there are multiple wires with most counterparties _but not with the original seeder_ (the one that looks like a face, with 196 transactions). George and I noticed this behaviour consistently over multiple browsers.

Hypothesis:
* The seeder always has data that I need, so I keep requesting data from them, the torrent wire stays open, and the channel stays alive
* Other peers sometimes have data for me, and sometimes don't. When they don't have data for me, I don't request data from them, the torrent wire drops, and the channel is left in a disconnected state.

Possible fixes:
1. We should handle closing the channel in the case where someone doesn't have data for you for some time. This should happen before the torrent timeout kicks in. This would lead to the channels ending in a closed state, instead of in a disconnected state
2. In some cases, we might still end up with an open channel without a torrent wire. It's probably worth checking to see if there are open channels with a given peer, in a given direction (send/receive) before setting up a new one. Even if you don't want to reuse these channels, you could use this opportunity to close them. (But we should probably reuse, if we can.)

![Screen Shot 2020-05-28 at 10 46 35 AM](https://user-images.githubusercontent.com/29596/83126351-9912a880-a0d0-11ea-848e-5dc9c8d09979.png)

**Comment by snario** [comment]
>  In some cases, we might still end up with an open channel without a torrent wire. It's probably worth checking to see if there are open channels with a given peer, in a given direction (send/receive) before setting up a new one. Even if you don't want to reuse these channels, you could use this opportunity to close them. (But we should probably reuse, if we can.)

We've decided not to do this in v1, but the work is there in #2004 ([`george/reuse-channels`](https://github.com/statechannels/monorepo/tree/george/reuse-channels))

**Comment by geoknee** [comment]
As far as I know we aren't seeing this problem any more.
