### ISSUE TITLE
[embedded-wallet] Set explicit amount of ETH to allocate in "Allow" button

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#286]
i.e. `Allow 0.2 ETH` if the slider is set to `0.2`.

![image](https://user-images.githubusercontent.com/118913/67712318-84d3c500-f9a2-11e9-8cac-9191e1dc87d5.png)

**Comment by snario** [comment]
I think the distinction between the "statechannels.com wants to allocate" and "Recommended amount: 0.2 ETH of your send" is a bit confusing. The key operator variable here are:

1. Who is asking for an allotment (statechannels.com)
2. An allotment of what (your Send Bandwidth or your Receive Bandwidth or BOTH (most likely))
3. How much for each Bandwidth type

We also probably want some kind of FAQ page, or maybe a tooltip to explain what the heck "bandwidth" is because I bet no one will have a clue on first glance.

**Comment by joelalejandro** [comment]
@snario This feedback looks great, but I think we're mixing up things. Bandwidth is a concept of the Web3Torrent domain, it has no place in the Embedded Wallet. If we want to feature it in this UI, we might want to consider a way for the dApp to customize the text in this dialog box.

A FAQ page or a tooltip would be nice too, but it's all part of the Web3Torrent project.

**Comment by snario** [comment]
I think there are two types of bandwidth concepts. Bandwidth is also a wallet concept; the bandwidth that you allot for an application to control of the funds within your channel with the hub.

For example if you have 5 ETH in your channel with a hub, and the hub has 5 ETH in that channel with you, then you have 5 ETH of Send Bandwidth and 5 ETH of Receive Bandwidth. Any application might use any amount of the Send and Receive bandwidth.

This is called bandwidth because the hub needs to lock some of its collateral in its channel with you for to a particular browser tab -- in this case Web3Torrent
