### ISSUE TITLE
[web3torrent] Spike a per-piece payment model

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#324]
Expands from #264.

The purpose of this issue is to spike a per-piece payment model.

In this payment model, the file gets split by a fixed number of pieces and the leecher will pay up-front before receiving the data chunks of that piece. To keep the download going as uninterrupted as possible, the leecher would start the payment request near the end of the current piece.

To complete a proof of concept for the model, the following steps are required:

- [ ] Figure out how to set a fixed number of pieces
- [ ] Extend WebTorrent's data flow to execute a callback function that determines if data can be transferred
- [ ] Mockup the necessary UI changes

**Comment by andrewgordstewart** [comment]
> Figure out how to set a fixed number of pieces

My understanding is that this is entirely determined by the torrent file. A torrent file specifies the SHA1 hash of the pieces of the file, and the number of such hashes is equal to the number of pieces. The person who creates the torrent file can choose the `pieceSize`, if they wish. But if there's some torrent floating around in the network, the leecher can't then choose how big the pieces should be.

This would be possible in the v2 bittorrent protocol, but I don't think webtorrent supports this.

> Extend WebTorrent's data flow to execute a callback function that determines if data can be transferred

Can you clarify what this means?

**Comment by joelalejandro** [comment]
@spersico looked into this and while we can choose the `pieceSize` on torrent creation, you're correct, the leecher doesn't get a say on it. And I've verified that `webtorrent` uses the v1 protocol.

About the data flow, we have custom event handlers at the `wire` (protocol) level that allows us to decide if and when data should be transferred between peers. We'd build upon that so Web3Torrent can tell the protocol if the payment was done, so it can release the data or not.

**Comment by andrewgordstewart** [comment]
I've written some clarification over [here](https://github.com/statechannels/monorepo/issues/264). It doesn't make sense to pay a single peer for a single piece. For example, you might want to request chunks from a given piece from more than one peer.

Here's is a possible payment and choking algorithm in a piece-based model
### Paying
p1) Bob sends some ether along with an `interested` message
p2) When he receives data, he sends more ether
p3) When he is uninterested, he requests a refund for unused funds

### Choking
c1) Alice unchokes the four peers that currently have the largest balance with her.
c2) She adds to the balance when she receives a payment
c3) She subtracts from the balance when she sends data
c4) When she sends a `choked` message, she returns any unused funds.

In addition, she maintains a blacklist of people who refused to return a refund at step (p3). She always chokes these people.

The bittorrent choking algorithm places value entirely on a download rate. This choking algorithm is similar, but places value entirely on the current opportunity to earn ether.

There are some problems with this solution as is, such as:
- How much should Bob send with his `interested` message?

**Comment by spersico** [comment]
Yesterday, @joelalejandro and I discussed this, and this is what I've got from that talk:

Even when we break a 10mb file into 10 pieces, the chunks to be sent will be subsets of a piece, of a maximum of 16kib. I tested and confirmed this behaviour yesterday with our library.

Even more, the pieces, once defined by the first seeder, can't be changed afterwards by other seeders.

Joel and I agree that a per-request model, **it's not** a good approach unless we can limit the number of requests involved to download a file, to a not-so-big amount, so that the back and forward between peers will not hurt the speed of the download. Especially on non-trivially sized torrents (1mb and beyond).

Having already set the piece size, we could look into changing the chunk size from 16kib to whatever the size of the piece we set, so that requests are much fewer and so, on each request, the leech asks for a piece, and after that piece is received, the leech pays for another, and so on.
To be honest, I'm wary of changing the block size, as it is a standard for BitTorrent, for stability and torrent-life-span reasons.

On the other side, if we don't use a per-request payment model, we start to talk about buffer/balance model, and the two approaches begin to vary mostly in your second question in [#264](https://github.com/statechannels/monorepo/issues/264#issuecomment-548698798), or, in other words, what should the leecher pay for? A piece? A random amount of bytes? The entire file?

It is my opinion (and @joelalejandro's, I think) that at this point of the discussion, this approach it's not so different from #325, if we set the minimum price to transfer funds for, for a torrent is the piece size of that torrent.

**Comment by andrewgordstewart** [comment]
> Yesterday, @joelalejandro and I discussed this, and this is what I've got from that talk:
> 
> Even when we break a 10mb file into 10 pieces, the chunks to be sent will be subsets of a piece, of a maximum of 16kib. I tested and confirmed this behaviour yesterday with our library.

Is this because a chunk has to fit inside a TCP packet? That's how I understood it, but I couldn't confirm it.

> 
> Joel and I agree that a per-request model, **it's not** a good approach unless we can limit the number of requests involved to download a file, to a not-so-big amount, so that the back and forward between peers will not hurt the speed of the download. Especially on non-trivially sized torrents (1mb and beyond).

I don't think round trips are so detrimental to download size per se, since the protocol is built around many round-trip `request`->`piece` exchanges. I think the only performance issue is with choking after sending every chunk, since unchoking happens at a set interval.

> 
> Having already set the piece size, we could look into changing the chunk size from 16kib to whatever the size of the piece we set, so that requests are much fewer and so, on each request, the leech asks for a piece, and after that piece is received, the leech pays for another, and so on.
> To be honest, I'm wary of changing the block size, as it is a standard for BitTorrent, for stability and torrent-life-span reasons.

:+1: Agree with this. Plus, I'm not even sure if it's possible (see above)

>  what should the leecher pay for? A piece? A random amount of bytes? The entire file?

A simple answer is:
- the leecher pays a constant price per chunk, where chunks are almost always 16 kB (except at the end of a file

I can't figure it out for myself, but is it possible to trigger a callback each time you send a `request` message? Or, even better, can you decorate a `request` message with some extra information?

If so, you simply send some eth along with your request message by including the next state in your payment channel. It could look something like this:

```
export abstract class PaidStreamingExtension implements Extension {
  // ...
  request() {
    this.sendPayment();
    this.wire.request();
    this.executeExtensionCommand(PaidStreamingExtensionNotices.START);
  }
}
```

**Comment by spersico** [comment]
> Is this because a chunk has to fit inside a TCP packet? That's how I understood it, but I couldn't confirm it.

I believe so, yes. I couldn't confirm it either, but it seems fairly possible.

>I don't think round trips are so detrimental to download size per se since the protocol is built around many round-trip request->piece exchanges. I think the only performance issue is with choking after sending every chunk, since unchoking happens at a set interval.

Remember that each leecher makes around 4-5 requests of chunks at the same time so that a stable and fast connection is made, and the seeder responds and balances the requests and responses using the BitTorrent mechanisms made for that (chocking is one of them).

Also, Web3Torrent choking is not the same than the original BitTorrent choking. This is where Web3Torrent introduces changes to the protocol, as we are using the choking messages, and internal client logic, to effectively block entirely all uploads from a seeder to a certain leecher. This means that unchoking a peer is not an immediate process since it involves the seeder putting the leecher in it's "Good Boys List" (Boys who Paid, I mean), and letting the leecher know about it, and the leecher cleaning the dropped/reserved requests and resending them to the seeder. Because requests and wires get dropped after a while and the leecher is the one who knows best what does it need to complete the file, it's the leecher who needs to resend the requests. This involves a delay of around 10 seconds (I don't remember exactly though) for the normal flow of data to begin.

> I can't figure it out for myself, but is it possible to trigger a callback each time you send a request message? 

I believe so, by making a custom request implementation, or listening for changes in the hash table but I don't quite understand why would you want to do that. Because, yes, I think that we could make the funds transfer together on a callback to the request sent, but those funds would almost always arrive _after_ the request, resulting in the leecher choking the connection. And remember that leechers try to send 4-5 requests at a time to each seeder. I'm not clear what would be the use of this.

> Or, even better, can you decorate a request message with some extra information?

Maybe? with a custom wire implementation, we could try...  but according to https://www.bittorrent.org/beps/bep_0003.html the request contains "index, begin, and length", and this payload is encoded, so I'm not sure if this would be a good approach, as I'm pretty sure that this would make Web3Torrent incompatible with other torrents. This is were many Torrent Clients check if the 16kiB is respected or not, and I read that some of them enforce this, so I'm not sure how they would handle having an extra field.


> A simple answer is:
>
> - the leecher pays a constant price per chunk, where chunks are almost always 16 kB (except at the end of a file

Then I believe that we are talking about the [Buffer/Balance based payment model](https://github.com/statechannels/monorepo/issues/325), aren't we?

**Comment by junjizhi** [comment]
@spersico Any more update on this issue? Can we move this issue to done in web3torrent project board?

**Comment by spersico** [comment]
@junjizhi Sure! I'll close it now
