### ISSUE TITLE
rps is broken

### ISSUE THREAD

**Issue by junjizhi** [statechannels/monorepo#955]
I tried playing the game with two Chrome tabs but saw the below error. And the page stalled here forever: 

<img width="1439" alt="rps-screenshot" src="https://user-images.githubusercontent.com/2715151/73602801-59cfb300-4547-11ea-9f30-1840d82f7824.png">

Did I do something wrong?

Environment: 
Mac OS 10.15.3
Chrome: Version 79.0.3945.130 (Official Build) (64-bit)
MetaMask: 7.7.4
Ropsten Testnet address: https://ropsten.etherscan.io/address/0x437864550474980e76f4559ee9b10e96b28ea6b5

**Comment by snario** [comment]
Hey @junjizhi thanks for reporting this! I’ll have a look in the morning, that’s strange.

**Comment by geoknee** [comment]
- I confirmed this behaviour on `rps.statechannels.org`
- It is a `wallet` issue rather than an `rps` issue: https://github.com/statechannels/monorepo/blob/f481f1e1ba487e7f901235b3308c97df49ef0fe0/packages/wallet/src/redux/protocols/virtual-funding/reducer.ts#L139 apparently one of these strings in the `destinations` array is `null`, which causes an error when we try to check its length inside the called function.
- I could _not_ reproduce the error locally on the `deploy` branch

One thing we could do is re-deploy `rps` , `wallet`, and `hub` by pushing latest `master` to `deploy` branch.

**Comment by snario** [comment]
I have re-deployed `rps` and `wallet`

**Comment by geoknee** [comment]
Good news: no more errors in the console. 
Bad news: things still hanging at "Advancing Channel" stage.

@snario could this be a hub issue? I notice there are some messages addressed to the hub in firebase that have not been picked up.

**Comment by snario** [comment]
Just redeployed the `hub` too, seems to be working now

**Comment by geoknee** [comment]
@snario I am seeing the original error again.

**Comment by snario** [comment]
@geokneee @junjizhi can you try once more now? I just reset any local caches, ran through the entire workflow, and saw no errors.
<img width="962" alt="Screen Shot 2020-02-05 at 09 26 04" src="https://user-images.githubusercontent.com/1933029/73866452-bb1ead00-47f9-11ea-90b6-28dc63ac518f.png">
<img width="961" alt="Screen Shot 2020-02-05 at 09 26 16" src="https://user-images.githubusercontent.com/1933029/73866460-beb23400-47f9-11ea-958e-c8e28beea1e5.png">
<img width="961" alt="Screen Shot 2020-02-05 at 09 26 56" src="https://user-images.githubusercontent.com/1933029/73866464-bf4aca80-47f9-11ea-9596-944a4e3847a1.png">

**Comment by junjizhi** [comment]
@snario Hmm.. still errors out after clearing all my local cookies:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/2715151/73868594-bc120780-4816-11ea-837f-166cb81a2f36.png">

**Comment by geoknee** [comment]
I think I know what causes this problem: the wallet is not currently calling `window.ethereum.enable()` before trying to grab the selected address from metamask. @junjizhi you can manually add `wallet.statechannels.org` as a "connection" in metamask. I tried this and the errors went away.

Local developed won't see this issue because the wallet is served from the same domain as the `rps` app.

Will get to work on a proper fix.

**Comment by geoknee** [comment]
@junjizhi recent fix has been deployed, and it seems to work for me. Let me know if you still have issues.

**Comment by junjizhi** [comment]
@geoknee Sorry to reply. I was traveling for the past two weeks. 

Confirmed that the issue is fixed. The game works for me now.
